In [ ]:
!pip install -U sentence-transformers

     |████████████████████████████████| 79 kB 3.7 MB/s 
     |████████████████████████████████| 3.5 MB 11.4 MB/s 
     |████████████████████████████████| 1.2 MB 49.6 MB/s 
     |████████████████████████████████| 67 kB 4.9 MB/s 
     |████████████████████████████████| 6.5 MB 40.7 MB/s 
     |████████████████████████████████| 596 kB 45.7 MB/s 
     |████████████████████████████████| 895 kB 48.1 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.0-py3-none-any.whl size=120747 sha256=0aa5d9f378b6f19895f5229ae6c93e07171e32e058ab50c1e20382b40a900424
  Stored in directory: /root/.cache/pip/wheels/83/c0/df/b6873ab7aac3f2465aa9144b6b4c41c4391cfecc027c8b07e7
Successfully built sentence-transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
import torch

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("vinai/phobert-base")

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.60k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/557 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/543M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/895k [00:00<?, ?B/s]

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/vinai_phobert-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
sentences = ["Anh nhớ em.",
             "Hôm nay trời có mưa không?",
             "Anh muốn cưới em.",
             "Dạo này MU đá đần nhỉ!",
             "Lúc nào cũng tấu hài.",
             "Yêu nhau nhé bạn thân."]

In [ ]:
# Install the vncorenlp python wrapper
!pip3 install vncorenlp

# Download VnCoreNLP-1.1.1.jar & its word segmentation component (i.e. RDRSegmenter) 
!mkdir -p vncorenlp/models/wordsegmenter
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/vi-vocab
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/wordsegmenter.rdr
!mv VnCoreNLP-1.1.1.jar vncorenlp/ 
!mv vi-vocab vncorenlp/models/wordsegmenter/
!mv wordsegmenter.rdr vncorenlp/models/wordsegmenter/

     |████████████████████████████████| 2.6 MB 5.3 MB/s 
  Created wheel for vncorenlp: filename=vncorenlp-1.0.3-py3-none-any.whl size=2645951 sha256=4a7239c4ce5676134b93a4f234dac8d1de510b52c511679bde9e8a6a3eb11402
  Stored in directory: /root/.cache/pip/wheels/0c/d8/f2/d28d97379b4f6479bf51247c8dfd57fa00932fa7a74b6aab29
Successfully built vncorenlp
--2022-03-03 08:43:48--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27412575 (26M) [application/octet-stream]
Saving to: ‘VnCoreNLP-1.1.1.jar’

VnCoreNLP-1.1.1.jar 100%[===================>]  26.14M   167MB/s    in 0.2s    

2022-03-03 08:43:49 (167 MB/s) - ‘VnCoreNLP-1.1.1.jar’ saved [27412575/27412575]

--2022-03-03 08:43:49-- 

In [ ]:
from vncorenlp import VnCoreNLP
rdrsegmenter = VnCoreNLP("/content/vncorenlp/VnCoreNLP-1.1.1.jar", annotators = "wseg", max_heap_size = "-Xmx500m")

In [ ]:
sent = rdrsegmenter.tokenize("Có lẽ em yêu anh nhiều quá, nên là em chẳng dám buông ra.")
sent = " ".join(sent[0])

In [ ]:
sent

'Có_lẽ em yêu anh nhiều quá , nên là em chẳng dám buông ra .'

In [ ]:
lst_sent = []

In [ ]:
for sentence in sentences:
  sent = rdrsegmenter.tokenize(sentence) 
  sent = " ".join(sent[0])
  lst_sent.append(sent)

In [ ]:
lst_sent

['Anh nhớ em .',
 'Hôm_nay trời có mưa không ?',
 'Anh muốn cưới em .',
 'Dạo này MU đá đần nhỉ !',
 'Lúc_nào cũng tấu hài .',
 'Yêu nhau nhé bạn thân .']

In [ ]:
#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)
#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", torch.tensor(embedding).size())
    print("")

Sentence: Anh nhớ em.
Embedding: torch.Size([768])

Sentence: Hôm nay trời có mưa không?
Embedding: torch.Size([768])

Sentence: Anh muốn cưới em.
Embedding: torch.Size([768])

Sentence: Dạo này MU đá đần nhỉ!
Embedding: torch.Size([768])

Sentence: Lúc nào cũng tấu hài.
Embedding: torch.Size([768])

Sentence: Yêu nhau nhé bạn thân.
Embedding: torch.Size([768])



In [ ]:
type(embeddings)

numpy.ndarray

In [ ]:
embeddings[0]

array([ 4.55204137e-02, -1.11558318e-01,  9.64874029e-02, -1.02039136e-01,
       -2.49191344e-01, -3.02540183e-01,  4.99549121e-01,  3.00113738e-01,
        1.99477956e-01,  2.12457657e-01,  1.12645082e-01,  8.71840343e-02,
        1.33903280e-01, -7.44948909e-02, -1.63583040e-01, -1.40569523e-01,
       -5.49635231e-01,  2.37735957e-02, -1.70515165e-01, -1.44881353e-01,
       -3.25253129e-01, -1.88416913e-01,  2.70218909e-01,  3.54552388e-01,
       -2.80720651e-01, -2.88928628e-01,  3.02744657e-01,  1.85979411e-01,
       -2.16277495e-01, -3.70335691e-02,  8.63247458e-03,  1.12470984e-02,
       -3.64068225e-02,  2.04314485e-01,  5.64132154e-01,  6.62955821e-01,
       -8.61346945e-02, -2.11421862e-01,  2.04050943e-01,  4.02619511e-01,
       -6.00596778e-02,  2.44840816e-01,  2.74267465e-01, -3.45479876e-01,
       -1.84922833e-02,  2.43950784e-01,  2.10613802e-01, -1.50375351e-01,
       -1.03752971e-01,  2.10212246e-01, -2.29856357e-01, -4.49021786e-01,
       -3.11822325e-01, -

In [ ]:
torch.tensor(embeddings[0]).size()

torch.Size([768])

In [ ]:
model_embeddings = model.encode(sentences)
model_embeddings

array([[ 0.04552041, -0.11155832,  0.0964874 , ..., -0.07163475,
         0.17043225,  0.148131  ],
       [-0.06146888,  0.1577423 , -0.16066913, ...,  0.04836295,
        -0.20426662,  0.30635697],
       [-0.04903405,  0.11510581,  0.01049469, ..., -0.09953833,
        -0.02165431,  0.44285995],
       [-0.24567923,  0.19206475, -0.06068562, ...,  0.04219402,
         0.04336961,  0.26665452],
       [-0.0815338 , -0.16921446, -0.2472795 , ...,  0.13181147,
        -0.04596098, -0.1183292 ],
       [-0.117897  , -0.03193529,  0.03479276, ...,  0.04708387,
        -0.1225488 ,  0.01275989]], dtype=float32)

In [ ]:
torch.tensor(model_embeddings).size()

torch.Size([6, 768])

In [ ]:
type(model_embeddings)

numpy.ndarray

In [ ]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity 

Let's calculate cosine similarity for sentence `0`:

In [ ]:
cosine_similarity([model_embeddings[0]],model_embeddings[1:])

array([[0.4300465 , 0.82831895, 0.4167831 , 0.3960988 , 0.5843199 ]],
      dtype=float32)

In [ ]:
rdrsegmenter.tokenize("Chàng trai Nghệ An khởi nghiệp từ thịt chó.")

[['Chàng', 'trai', 'Nghệ_An', 'khởi_nghiệp', 'từ', 'thịt', 'chó', '.']]